//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausencia
    {
        public int IdAusencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Ausente { get; set; }
        public int IdCursosEstudiantes { get; set; }
    
        public virtual CursosEstudiante CursosEstudiante { get; set; }
    }
}
