//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosEstudiante
    {
        public CursosEstudiante()
        {
            this.Ausencias = new HashSet<Ausencia>();
        }
    
        public int IdCursosEstudiantes { get; set; }
        public int IdCurso { get; set; }
        public int IdEstudiante { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public int IdCursosHorarios { get; set; }
    
        public virtual ICollection<Ausencia> Ausencias { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
