//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosProfesor
    {
        public int IdCursosHorarios { get; set; }
        public int IdProfesor { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public int LimiteAusencias { get; set; }
    
        public virtual Profesore Profesore { get; set; }
        public virtual CursosHorario CursosHorario { get; set; }
    }
}
