//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public Distrito()
        {
            this.Estudiantes = new HashSet<Estudiante>();
        }
    
        public int IdDistrito { get; set; }
        public string Nombre { get; set; }
        public int IdCanton { get; set; }
    
        public virtual Cantone Cantone { get; set; }
        public virtual ICollection<Estudiante> Estudiantes { get; set; }
    }
}
