//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CursosEntity : DbContext
    {
        public CursosEntity()
            : base("name=CursosEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CursosEstudiante> CursosEstudiantes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Ausencia> Ausencias { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<CursosHorario> CursosHorarios { get; set; }
        public virtual DbSet<CursosProfesor> CursosProfesors { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
    }
}
