//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int IdParametro { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Cedula { get; set; }
        public string RutaLogo { get; set; }
        public string Telefono { get; set; }
        public string RutaSistema { get; set; }
        public string HostCorreo { get; set; }
        public int PortCorreo { get; set; }
        public int TimeOutCorreo { get; set; }
        public string UserNameCorreo { get; set; }
        public string PasswordCorreo { get; set; }
        public string FromCorreo { get; set; }
        public string DisplayNameCorreo { get; set; }
        public string CorreoContactoRespaldos { get; set; }
    }
}
