//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int IdRole { get; set; }
        public string Descripcion { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
